### ISSUE TITLE
Can't access trac "Session ID not set"

### ISSUE THREAD

**Issue by AmiZya** [django/code.djangoproject.com#25]
Hello, 

I can't access trac website. I got the following error:
 
```
Traceback (most recent call last):
  File "/home/www/trac/venv/local/lib/python2.7/site-packages/trac/web/api.py", line 514, in send_error
    data, 'text/html')
  File "/home/www/trac/venv/local/lib/python2.7/site-packages/trac/web/chrome.py", line 968, in render_template
    message = Markup(req.session.pop('chrome.%s.%d'
  File "/home/www/trac/venv/local/lib/python2.7/site-packages/trac/web/api.py", line 316, in __getattr__
    value = self.callbacks[name](self)
  File "/home/www/trac/venv/local/lib/python2.7/site-packages/trac/web/main.py", line 268, in _get_session
    return Session(self.env, req)
  File "/home/www/trac/venv/local/lib/python2.7/site-packages/trac/web/session.py", line 206, in __init__
    self.get_session(sid)
  File "/home/www/trac/venv/local/lib/python2.7/site-packages/trac/web/session.py", line 235, in get_session
    self.bake_cookie()
  File "/home/www/trac/venv/local/lib/python2.7/site-packages/trac/web/session.py", line 214, in bake_cookie
    assert self.sid, 'Session ID not set'
AssertionError: Session ID not set
```

But I can access it in private mode

Thanks,

**Comment by bmispelon** [comment]
Hi,

It's been a while, are you still having this issue?
It seems it might have been a cookie issue. Have you tried deleting any cookie associated with `code.djangoproject.com`.

Thanks!

**Comment by timgraham** [comment]
Closing absent instructions to reproduce the issue.
